DROP SEQUENCE  BATCH_STAGING_SEQ ;
DROP SEQUENCE  CUSTOMER_SEQ ;
DROP TABLE  BATCH_STAGING ;
DROP TABLE  CUSTOMER ;
DROP TABLE  ERROR_LOG ;

CREATE SEQUENCE CUSTOMER_SEQ START WITH 5;
CREATE SEQUENCE BATCH_STAGING_SEQ START WITH 0 MINVALUE 0;

CREATE TABLE BATCH_STAGING  (
	ID NUMBER(38)  NOT NULL PRIMARY KEY ,  
	JOB_ID NUMBER(38) NOT NULL,
	VALUE BLOB NOT NULL,
	PROCESSED CHAR(1) NOT NULL
) ;

CREATE TABLE CUSTOMER (
	ID NUMBER(38)  NOT NULL PRIMARY KEY ,  
	VERSION NUMBER(38) ,
	FIRSTNAME VARCHAR2(45) ,
	LASTNAME VARCHAR2(45) ,
	AGE NUMBER(18) ,
	GENDER CHAR(1)
) ;
 
INSERT INTO CUSTOMER (ID, VERSION, FIRSTNAME, LASTNAME, AGE, GENDER) VALUES (1, 0, 'fcustomer1', 'lcustomer1', 10, 'M');
INSERT INTO CUSTOMER (ID, VERSION, FIRSTNAME, LASTNAME, AGE, GENDER) VALUES (2, 0, 'fcustomer2', 'lcustomer2', 20, 'F');
INSERT INTO CUSTOMER (ID, VERSION, FIRSTNAME, LASTNAME, AGE, GENDER) VALUES (3, 0, 'fcustomer3', 'lcustomer3', 30, 'F');
INSERT INTO CUSTOMER (ID, VERSION, FIRSTNAME, LASTNAME, AGE, GENDER) VALUES (4, 0, 'fcustomer4', 'lcustomer4', 40, 'M');

CREATE TABLE ERROR_LOG  (
		JOB_NAME CHAR(20) ,
		STEP_NAME CHAR(20) ,
		MESSAGE VARCHAR(300) NOT NULL
) ;
